#db:
#  image: mysql:5.6
#  environment:
#    MYSQL_ROOT_PASSWORD: weblate
#    MYSQL_USER: weblate
#    MYSQL_PASSWORD: weblate
#    MYSQL_DATABASE: weblate
#  volumes:
#    - var/lib/mysql/:/var/lib/mysql/
#  command: mysqld -C utf8 --collation-server utf8_general_ci

memcached:
  image: memcached

weblatedocker:
  image: okaufmann/weblate-docker:latest
  #build: ../../build/weblate
  links:
    #- db:db
    - memcached:memcached
  ports:
    - 8080:8000
  volumes:
   - var/lib/weblate:/var/lib/weblate
   - var/lib/git:/var/lib/git
